modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "searchablecontainers"
version = "${version}"
displayName = "Searchable Containers"
authors = "AreUThreateningMe"
description = '''
Searchable containers is small client side gui mod that adds a search bar just above the players open container.
'''
#logoFile = ""

[[dependencies.searchablecontainers]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.searchablecontainers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
